"""Create initial database schema

Revision ID: e0e02bc8fa07
Revises:
Create Date: 2025-09-22 02:27:18.657423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID

# revision identifiers, used by Alembic.
revision: str = 'e0e02bc8fa07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- Users and Authentication ---
    op.create_table('users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(length=320), nullable=False),
        sa.Column('hashed_password', sa.String(length=1024), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_verified', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_superuser', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    op.create_table('user_details',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('username', sa.String(length=24), nullable=False),
        sa.Column('profile_info', sa.String(length=500), nullable=True),
        sa.Column('avatar_url', sa.String(length=255), nullable=True),
        sa.Column('last_username_change', sa.DateTime(timezone=True), nullable=True),
        sa.Column('email_notifications_enabled', sa.Boolean(), nullable=False),
        sa.Column('in_app_notifications_enabled', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
        sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_details_username'), 'user_details', ['username'], unique=True)

    op.create_table('username_blocklist',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('username', sa.String(length=24), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('original_user_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['original_user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_username_blocklist_username'), 'username_blocklist', ['username'], unique=True)
    
    op.create_table('oauth_accounts',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('oauth_name', sa.String(length=100), nullable=False),
        sa.Column('access_token', sa.String(length=1024), nullable=False),
        sa.Column('expires_at', sa.Integer(), nullable=True),
        sa.Column('refresh_token', sa.String(length=1024), nullable=True),
        sa.Column('account_id', sa.String(length=320), nullable=False),
        sa.Column('account_email', sa.String(length=320), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
        sa.PrimaryKeyConstraint('oauth_name', 'account_id')
    )
    op.create_index(op.f('ix_oauth_accounts_account_id'), 'oauth_accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_oauth_name'), 'oauth_accounts', ['oauth_name'], unique=False)

    # --- Organizations and Memberships ---
    op.create_table('organizations',
        sa.Column('id', sa.UUID(), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('slug', sa.String(length=120), nullable=False),
        sa.Column('logo_url', sa.String(length=255), nullable=True),
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_unique_constraint(None, 'organizations', ['name'])


    op.create_table('user_organization_memberships',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('organization_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='cascade'),
        sa.PrimaryKeyConstraint('user_id', 'organization_id')
    )
    
    # --- Programs and Assets ---
    op.create_table('programs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('organization_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('slug', sa.String(length=120), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, default=None),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('organization_id', 'slug', name='uq_organization_program_slug')
    )


    op.create_table('asset_types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    asset_types_table = sa.table(
        "asset_types",
        sa.column("id", sa.Integer()),
        sa.column("name", sa.String()),
        sa.column("description", sa.String()),
    )
    op.bulk_insert(
        asset_types_table,
        [
            {"id": 1, "name": "url", "description": "A web application URL (e.g., https://example.com)."},
            {"id": 2, "name": "wildcard", "description": "A wildcard domain (e.g., *.example.com)."},
            {"id": 3, "name": "api", "description": "A specific API endpoint or a base URL for an API."},
            {"id": 4, "name": "mobile_ios", "description": "An iOS mobile application (App Store link or bundle ID)."},
            {"id": 5, "name": "mobile_android", "description": "An Android mobile application (Play Store link or package name)."},
            {"id": 6, "name": "source_code", "description": "A source code repository (e.g., a GitHub or GitLab URL)."},
            {"id": 7, "name": "ip_address", "description": "A specific IP address or a CIDR range (e.g., 192.168.1.0/24)."},
            {"id": 8, "name": "desktop_app", "description": "A downloadable desktop application (Windows, macOS, Linux)."},
            {"id": 9, "name": "other", "description": "Any other type of asset not covered by the above categories."},
        ],
    )

    op.create_table('rewards',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('program_id', sa.UUID(), nullable=False),
        sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', name='severity_enum'), nullable=False),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('program_assets',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('program_id', sa.UUID(), nullable=False),
        sa.Column('asset_type_id', sa.Integer(), nullable=False),
        sa.Column('identifier', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], ),
        sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint('uq_program_identifier', 'program_assets', ['program_id', 'identifier'])
    
    # --- Reports and Communication ---
    op.create_table('reports',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('program_id', sa.UUID(), nullable=False),
        sa.Column('hacker_id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=120), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('status', sa.Enum('received', 'in_review', 'accepted', 'rejected', 'duplicate', 'out_of_scope', 'resolved', name='report_status_enum'), nullable=False),
        sa.Column('severity', sa.Float(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['hacker_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('report_comments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('report_id', sa.UUID(), nullable=False),
        sa.Column('user_id', GUID(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('attachments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('uploader_id', sa.UUID(), nullable=False),
        sa.Column('file_path', sa.String(length=512), nullable=False),
        sa.Column('file_name', sa.String(length=255), nullable=False),
        sa.Column('mime_type', sa.String(length=100), nullable=False),
        sa.Column('file_size', sa.BigInteger(), nullable=False),
        sa.Column('checksum', sa.String(length=64), nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=False),
        sa.Column('entity_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attachments_entity_type_entity_id', 'attachments', ['entity_type', 'entity_id'], unique=False)

    op.create_table('report_assets',
        sa.Column('report_id', sa.UUID(), nullable=False),
        sa.Column('program_asset_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['report_id'], ['reports.id']),
        sa.ForeignKeyConstraint(['program_asset_id'], ['program_assets.id']),
        sa.PrimaryKeyConstraint('report_id', 'program_asset_id')
    )
    op.create_table('report_events',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('report_id', sa.UUID(), nullable=False),
        sa.Column('user_id', GUID(), nullable=True),
        sa.Column('event_type', sa.Enum('report_created', 'status_change', 'severity_change', 'comment', name='report_event_type_enum'), nullable=False),
        sa.Column('old_value', sa.Text(), nullable=True),
        sa.Column('new_value', sa.Text(), nullable=True),
        sa.Column('comment_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['comment_id'], ['report_comments.id'], ),
        sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    notification_types_table = sa.table(
        "notification_types",
        sa.column("id", sa.Integer()),
        sa.column("name", sa.String()),
        sa.column("description", sa.String()),
    )
    op.bulk_insert(
        notification_types_table,
        [
            {"id": 1, "name": "report_created", "description": "When a new report is submitted"},
            {"id": 2, "name": "status_changed", "description": "When report status changes"},
            {"id": 3, "name": "severity_changed", "description": "When report severity changes"},
            {"id": 4, "name": "comment_added", "description": "When a comment is added to a report"},
        ],
    )
    op.create_table('notifications',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', GUID(), nullable=False),
        sa.Column('notification_type_id', sa.Integer(), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('related_entity_id', sa.UUID(), nullable=True),
        sa.Column('is_read', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['notification_type_id'], ['notification_types.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('notifications', sa.Column('recipient_role', sa.String(length=20), nullable=False))
    op.create_table('refresh_tokens',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('token_hash', sa.String(length=64), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('csrf_token', sa.String(length=64), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('revoked', sa.Boolean(), nullable=False),
        sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('device_info', sa.JSON(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_username_blocklist_username'), table_name='username_blocklist')
    op.drop_table('username_blocklist')
    op.drop_column('notifications', 'recipient_role')
    op.drop_table('report_events')
    op.drop_table('report_assets')
    op.drop_index('ix_attachments_entity_type_entity_id', table_name='attachments')
    op.drop_table('attachments')
    op.drop_table('report_comments')
    op.alter_column('reports', 'severity',
               existing_type=sa.Float(),
               nullable=True)
    op.drop_table('reports')
    op.drop_constraint('uq_program_identifier', 'program_assets', type_='unique')
    op.drop_table('program_assets')
    op.drop_table('rewards')
    op.drop_table('asset_types')
    op.drop_table('programs')
    op.drop_table('user_organization_memberships')
    op.drop_constraint('organizations_name_key', 'organizations', type_='unique')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_oauth_accounts_oauth_name'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_account_id'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index(op.f('ix_user_details_username'), table_name='user_details')
    op.drop_column('user_details', 'avatar_url')
    op.alter_column('user_details', 'profile_info',
                    type_=sa.JSON(),
                    postgresql_using='profile_info::json')
    op.drop_column('user_details', 'in_app_notifications_enabled')
    op.drop_column('user_details', 'email_notifications_enabled')
    op.drop_constraint('notifications_notification_type_id_fkey', 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'notification_type_id')
    op.drop_column('notifications', 'is_read')
    op.add_column('notifications', sa.Column('notification_type', sa.Enum('report_created', 'status_changed', 'severity_changed', 'comment_added', name='notification_type_enum'), autoincrement=False, nullable=False))
    op.drop_table('notification_types')
    op.drop_table('user_details')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###