"""Add UserStats model

Revision ID: 85c78c7b9822
Revises: e0e02bc8fa07
Create Date: 2026-02-22 23:22:44.021262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c78c7b9822'
down_revision: Union[str, None] = 'e0e02bc8fa07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stats',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('total_reports', sa.Integer(), nullable=False),
    sa.Column('critical_bugs', sa.Integer(), nullable=False),
    sa.Column('high_bugs', sa.Integer(), nullable=False),
    sa.Column('medium_bugs', sa.Integer(), nullable=False),
    sa.Column('low_bugs', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_stats_total_score'), 'user_stats', ['total_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stats_total_score'), table_name='user_stats')
    op.drop_table('user_stats')
    # ### end Alembic commands ###
