"""soft_delete_programs

Revision ID: 922ca715b570
Revises: e0e02bc8fa07
Create Date: 2025-12-12 16:17:51.276854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '922ca715b570'
down_revision: Union[str, None] = 'e0e02bc8fa07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, default=None))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'deleted_at')
    # ### end Alembic commands ###
