from enum import Enum

class ErrorCode(str, Enum):
    # User related errors
    USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"
    USERNAME_CHANGE_RESTRICTED = "USERNAME_CHANGE_RESTRICTED"
    USERNAME_NOT_AVAILABLE = "USERNAME_NOT_AVAILABLE"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    
    # Auth related errors
    INVALID_TOKEN = "INVALID_TOKEN"
    REFRESH_TOKEN_MISSING = "REFRESH_TOKEN_MISSING"
    USER_INACTIVE = "USER_INACTIVE"
    LOGIN_FAILED = "LOGIN_FAILED"
    GOOGLE_LOGIN_FAILED = "GOOGLE_LOGIN_FAILED"
    INVALID_LOGIN_SESSION = "INVALID_LOGIN_SESSION"
    
    PROGRAM_ALREADY_EXISTS = "PROGRAM_ALREADY_EXISTS"
    DUPLICATE_ASSET_IDENTIFIERS = "DUPLICATE_ASSET_IDENTIFIERS"
    MAX_FILES_EXCEEDED = "MAX_FILES_EXCEEDED"
    
    # Organization related errors
    ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND"
    INVALID_LOGO_URL = "INVALID_LOGO_URL"
    NOT_ORG_MEMBER = "NOT_ORG_MEMBER"
    ORGANIZATION_ALREADY_EXISTS = "ORGANIZATION_ALREADY_EXISTS"
    
    # Program related errors
    PROGRAM_NOT_FOUND = "PROGRAM_NOT_FOUND"
    PROGRAM_MUST_HAVE_ASSET = "PROGRAM_MUST_HAVE_ASSET"
    PROGRAM_INACTIVE = "PROGRAM_INACTIVE"
    PROGRAM_DELETED = "PROGRAM_DELETED"
    
    # Report related errors
    REPORT_NOT_FOUND = "REPORT_NOT_FOUND"
    INVALID_ASSET_IDS = "INVALID_ASSET_IDS"
    COMMENT_NOT_FOUND = "COMMENT_NOT_FOUND"
    NOT_YOUR_COMMENT = "NOT_YOUR_COMMENT"
    CANNOT_EDIT_DELETED_PROGRAM = "CANNOT_EDIT_DELETED_PROGRAM"
    
    # Attachment/Asset related errors
    ATTACHMENT_NOT_FOUND = "ATTACHMENT_NOT_FOUND"
    
    # Generic errors
    BAD_REQUEST = "BAD_REQUEST"
    NOT_FOUND = "NOT_FOUND"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    INVALID_PARAMETERS = "INVALID_PARAMETERS"
