from enum import Enum

class ErrorCode(str, Enum):
    # User related errors
    USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"
    USERNAME_CHANGE_RESTRICTED = "USERNAME_CHANGE_RESTRICTED"
    USERNAME_NOT_AVAILABLE = "USERNAME_NOT_AVAILABLE"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    
    # Auth related errors
    INVALID_TOKEN = "INVALID_TOKEN"
    REFRESH_TOKEN_MISSING = "REFRESH_TOKEN_MISSING"
    USER_INACTIVE = "USER_INACTIVE"
    LOGIN_FAILED = "LOGIN_FAILED"
    GOOGLE_LOGIN_FAILED = "GOOGLE_LOGIN_FAILED"
    INVALID_LOGIN_SESSION = "INVALID_LOGIN_SESSION"
    
    PROGRAM_ALREADY_EXISTS = "PROGRAM_ALREADY_EXISTS"
    DUPLICATE_ASSET_IDENTIFIERS = "DUPLICATE_ASSET_IDENTIFIERS"
    MAX_FILES_EXCEEDED = "MAX_FILES_EXCEEDED"
    
    # Organization related errors
    ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND"
    INVALID_LOGO_URL = "INVALID_LOGO_URL"
    NOT_ORG_MEMBER = "NOT_ORG_MEMBER"
    ORGANIZATION_ALREADY_EXISTS = "ORGANIZATION_ALREADY_EXISTS"
    
    # Program related errors
    PROGRAM_NOT_FOUND = "PROGRAM_NOT_FOUND"
    PROGRAM_MUST_HAVE_ASSET = "PROGRAM_MUST_HAVE_ASSET"
    PROGRAM_INACTIVE = "PROGRAM_INACTIVE"
    PROGRAM_DELETED = "PROGRAM_DELETED"
    
    # Report related errors
    REPORT_NOT_FOUND = "REPORT_NOT_FOUND"
    INVALID_ASSET_IDS = "INVALID_ASSET_IDS"

    CANNOT_EDIT_DELETED_PROGRAM = "CANNOT_EDIT_DELETED_PROGRAM"
    
    # Attachment/Asset related errors
    ATTACHMENT_NOT_FOUND = "ATTACHMENT_NOT_FOUND"
    
    # Validation errors (for i18n in schemas)
    # Programs
    PROGRAM_NAME_TOO_SHORT = "PROGRAM_NAME_TOO_SHORT"
    PROGRAM_NAME_TOO_LONG = "PROGRAM_NAME_TOO_LONG"
    PROGRAM_DESCRIPTION_TOO_SHORT = "PROGRAM_DESCRIPTION_TOO_SHORT"
    PROGRAM_DESCRIPTION_TOO_LONG = "PROGRAM_DESCRIPTION_TOO_LONG"
    ASSET_IDENTIFIER_EMPTY = "ASSET_IDENTIFIER_EMPTY"
    ASSET_DESCRIPTION_TOO_LONG = "ASSET_DESCRIPTION_TOO_LONG"
    
    # Reports
    REPORT_TITLE_TOO_SHORT = "REPORT_TITLE_TOO_SHORT"
    REPORT_TITLE_TOO_LONG = "REPORT_TITLE_TOO_LONG"
    REPORT_SEVERITY_RANGE = "REPORT_SEVERITY_RANGE"
    REPORT_SEVERITY_DECIMALS = "REPORT_SEVERITY_DECIMALS"
    REPORT_DESCRIPTION_TOO_SHORT = "REPORT_DESCRIPTION_TOO_SHORT"
    REPORT_DESCRIPTION_TOO_LONG = "REPORT_DESCRIPTION_TOO_LONG"
    COMMENT_CONTENT_EMPTY = "COMMENT_CONTENT_EMPTY"
    COMMENT_CONTENT_TOO_LONG = "COMMENT_CONTENT_TOO_LONG"
    
    # Users
    USER_USERNAME_TOO_SHORT = "USER_USERNAME_TOO_SHORT"
    USER_USERNAME_TOO_LONG = "USER_USERNAME_TOO_LONG"
    USER_USERNAME_INVALID_PATTERN = "USER_USERNAME_INVALID_PATTERN"
    USER_USERNAME_RESERVED = "USER_USERNAME_RESERVED"
    USER_PROFILE_INFO_TOO_LONG = "USER_PROFILE_INFO_TOO_LONG"
    
    # Guest account errors
    GUEST_ACTION_FORBIDDEN = "GUEST_ACTION_FORBIDDEN"
    GUEST_REPORT_LIMIT = "GUEST_REPORT_LIMIT"
    GUEST_LOGIN_FAILED = "GUEST_LOGIN_FAILED"

    # CAPTCHA errors
    CAPTCHA_FAILED = "CAPTCHA_FAILED"
    
    # Generic errors
    BAD_REQUEST = "BAD_REQUEST"
    NOT_FOUND = "NOT_FOUND"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    INVALID_PARAMETERS = "INVALID_PARAMETERS"
